import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(4000),
  API_BASE_URL: z.string().url().default('http://localhost:4000'),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  JWT_SECRET: z.string().min(32),
  JWT_EXPIRES_IN: z.string().default('15m'),
  JWT_ISSUER: z.string().default('synapse-api'),
  JWT_AUDIENCE: z.string().default('synapse-web'),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_DEFAULT_MODEL: z.string().default('gpt-4.1-mini'),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_API_VERSION: z.string().default('2026-02-25.preview'),
  STRIPE_BASE_URL: z.string().url().default('https://api.stripe.com'),
  STRIPE_PRICE_LIGHT: z.string().optional(),
  STRIPE_PRICE_PRO: z.string().optional(),
  STRIPE_PRICE_PREMIUM: z.string().optional(),
  BILLING_REDIRECT_ALLOWED_ORIGINS: z.string().optional(),
  TELEGRAM_BOT_TOKEN: z.string().optional(),
  CORS_ORIGINS: z.string().optional(),
  REQUEST_BODY_LIMIT: z.string().default('1mb'),
  SYNAPSE_RUNTIME_URL: z.string().url().optional(),
  SYNAPSE_RUNTIME_SHARED_SECRET: z.string().min(32).optional(),
  SYNAPSE_RUNTIME_KEY_ID: z.string().default('platform'),
  SYNAPSE_RUNTIME_SIGNATURE_TOLERANCE_SECONDS: z.coerce.number().int().positive().default(300)
});
