ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "PlatformRole" ADD VALUE IF NOT EXISTS 'TESTER';

ALTER TABLE "User" ADD COLUMN "platformScopes" JSONB NOT NULL DEFAULT '{}';
